require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
