version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/cm
      - gem-cache:/gems
    env_file:
      - .env/development/web
      - .env/development/database
    networks:
      default:
        aliases:
          - web
  
  redis:
    image: redis
    networks:
      - default
    
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env/development/database
    networks:
      - default
      
  selenium-hub:
    image: selenium/hub
    container_name: cm-selenium
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    networks:
      - default
    environment:
     GRID_MAX_SESSION: 10
      
  selenium-chrome:
    image: selenium/node-chrome
    logging:
      driver: none
    links:
      - selenium-hub
    networks:
      - default
    depends_on:
      - selenium-hub
    ports:
      - "5900-5905:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

volumes:
  db-data:
  gem-cache:
