development:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
  channel_prefix: court_message_development

test:
  adapter: test

staging:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
  channel_prefix: court_message_staging

production:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
  channel_prefix: court_message_production
