name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop
